#Server socket
server.ws.port=8686
server.tcp.port=8889
server.udp.port=8890
server.id=1
server.type=ws

#number threads queue
server.queue.threads.size=50
server.queue.threads.queue.size=200

#number threads socket
server.socket.threads.size=10
server.socket.queue.size=50


# Public key
server.public.key=T7PfKrPGvK

# Queue
queue.username=admin
queue.virtualHost=/
queue.password=admin@2o23.hcm
queue.port=5672
queue.ip=192.168.201.16
queue.notification=QUEUE_NOTIFICATION
queue.process.tables=QUEUE_PROCESS_TABLE

# Rabbitmq config
rabbit.prefetch=10

# One Signal
onesignal.api-url=https://api.onesignal.com
onesignal.enabled=true
# App Mobile
onesignal.mobile.app-id=28fb9f8d-d42e-4293-bdfa-09d17b6eb0ac
onesignal.mobile.api-key=os_v2_app_fd5z7doufzbjhpp2bhixw3vqvrbkly4fwpleum5i5blcv6geocyiwclydvxwbfjwykarwq5dis2h2uzxs4ueoirq5pefounkgjgzfwq
# App View
onesignal.view.app-id=6e86c2fd-cd75-440d-9334-2165601e50cf
onesignal.view.api-key=os_v2_app_n2dmf7onovca3ezuefswahsqz43cpqjupymepgedbxribt2yij7ay6whvzdigauf3nt5e5jkth3s3h2jjsb3fyolmqsmuxxjxpdsxsa

# Redis
server.redis.threads.size=70
redis.type=1
redis.sentinel.host=127.0.0.1:26379,127.0.0.2:26379
redis.master.name=master
redis.host=localhost:6379
redis.password=admin123654